version: "3.8"

services:
  product-service:
    build:
      context: ./product-service
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    networks:
      - communication-network

  order-service:
    build:
      context: ./order-service
      dockerfile: Dockerfile
    ports:
      - "3001:3001"
    networks:
      - communication-network

networks:
  communication-network:
    driver: bridge
