version: "3.8"

services:
  # Service REST
  rest-service:
    build:
      context: ./rest-service
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    networks:
      - communication-network

  # Service gRPC
  grpc-service:
    build:
      context: ./grpc-service
      dockerfile: Dockerfile
    ports:
      - "50051:50051"
    networks:
      - communication-network

  # Service WebSocket
  websocket-service:
    build:
      context: ./websocket-service
      dockerfile: Dockerfile
    ports:
      - "8081:8080"
    networks:
      - communication-network

networks:
  communication-network:
    driver: bridge
